version: '2'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 hello:app
    volumes:
      - .:/opt/webapp
    ports:
      - '5000:5000'
    logging:
      driver: json-file
      options:
        max-size: 5m
